// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"spring-go-rpc/app/gen/go/system/service/conf"
	conf2 "spring-go-rpc/app/system/service/conf"
	"spring-go-rpc/app/system/service/internal/biz"
	"spring-go-rpc/app/system/service/internal/data"
	"spring-go-rpc/app/system/service/internal/server"
	"spring-go-rpc/app/system/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	nacosClientParam := conf2.NewNacosConf()
	discovery := data.NewDiscovery(nacosClientParam)
	userRepo := data.NewUserRepo(discovery, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	registrar := data.NewRegistrar(nacosClientParam)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
